import type { MenuItem, Category } from './types';

export const categories: { id: Category; label: string; icon: string }[] = [
  { id: 'all', label: 'All Items', icon: '🍽️' },
  { id: 'burgers', label: 'Burgers', icon: '🍔' },
  { id: 'pizza', label: 'Pizza', icon: '🍕' },
  { id: 'salads', label: 'Salads', icon: '🥗' },
  { id: 'sushi', label: 'Sushi', icon: '🍣' },
  { id: 'beverages', label: 'Beverages', icon: '🥤' },
  { id: 'desserts', label: 'Desserts', icon: '🍰' },
];

export const menuItems: MenuItem[] = [
  {
    id: 'b1',
    name: 'Classic Cheeseburger',
    description: 'Beef patty, melted cheddar, lettuce, tomato, house sauce',
    price: 7.50,
    category: 'burgers',
    image: 'https://images.pexels.com/photos/36869509/pexels-photo-36869509.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 12,
    rating: 4.8,
    tags: ['Bestseller'],
    popular: true,
  },
  {
    id: 'b2',
    name: 'Double Smash Burger',
    description: 'Two smashed patties, American cheese, pickles, onion jam',
    price: 9.50,
    category: 'burgers',
    image: 'https://images.pexels.com/photos/12653336/pexels-photo-12653336.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 15,
    rating: 4.7,
    tags: ['Hearty'],
  },
  {
    id: 'b3',
    name: 'Bacon BBQ Burger',
    description: 'Crispy bacon, BBQ sauce, onion rings, smoked cheese',
    price: 10.50,
    category: 'burgers',
    image: 'https://images.pexels.com/photos/7786563/pexels-photo-7786563.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 14,
    rating: 4.6,
    tags: ['New'],
  },
  {
    id: 'p1',
    name: 'Pepperoni Pizza Slice',
    description: 'Classic pepperoni with mozzarella on hand-tossed dough',
    price: 4.50,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/5903275/pexels-photo-5903275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 10,
    rating: 4.9,
    tags: ['Bestseller'],
    popular: true,
  },
  {
    id: 'p2',
    name: 'Margherita Slice',
    description: 'Fresh basil, mozzarella, tomato sauce, olive oil drizzle',
    price: 4.00,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/35123979/pexels-photo-35123979.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 10,
    rating: 4.5,
    tags: ['Vegetarian'],
  },
  {
    id: 'p3',
    name: 'Meat Lover\'s Slice',
    description: 'Sausage, ham, pepperoni, bacon, extra cheese',
    price: 5.50,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/19786200/pexels-photo-19786200.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 12,
    rating: 4.7,
    tags: ['Hearty'],
  },
  {
    id: 's1',
    name: 'Grilled Chicken Salad',
    description: 'Mixed greens, grilled chicken, cherry tomatoes, vinaigrette',
    price: 8.50,
    category: 'salads',
    image: 'https://images.pexels.com/photos/842545/pexels-photo-842545.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 8,
    rating: 4.6,
    tags: ['Healthy'],
    popular: true,
  },
  {
    id: 's2',
    name: 'Caprese Salad',
    description: 'Mozzarella, cherry tomatoes, nuts, fresh basil, balsamic',
    price: 7.50,
    category: 'salads',
    image: 'https://images.pexels.com/photos/33323285/pexels-photo-33323285.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 6,
    rating: 4.4,
    tags: ['Vegetarian'],
  },
  {
    id: 's3',
    name: 'Fruit & Veggie Bowl',
    description: 'Seasonal fruits, pomegranate, pears, mixed greens',
    price: 6.50,
    category: 'salads',
    image: 'https://images.pexels.com/photos/16313570/pexels-photo-16313570.png?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 5,
    rating: 4.3,
    tags: ['Vegan'],
  },
  {
    id: 'su1',
    name: 'Avocado Sushi Roll',
    description: 'Fresh avocado, rice, carrot, wrapped in nori — 8 pieces',
    price: 6.50,
    category: 'sushi',
    image: 'https://images.pexels.com/photos/18891321/pexels-photo-18891321.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 10,
    rating: 4.5,
    tags: ['Vegetarian'],
  },
  {
    id: 'su2',
    name: 'Crispy Fried Roll',
    description: 'Tempura shrimp, spicy mayo, topped with crispy onions — 6 pieces',
    price: 8.50,
    category: 'sushi',
    image: 'https://images.pexels.com/photos/11064614/pexels-photo-11064614.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 12,
    rating: 4.8,
    tags: ['Bestseller'],
    popular: true,
  },
  {
    id: 'su3',
    name: 'Assorted Sushi Platter',
    description: 'Chef\'s selection of 12 pieces with salmon, tuna, and veggie',
    price: 14.00,
    category: 'sushi',
    image: 'https://images.pexels.com/photos/28291549/pexels-photo-28291549.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 15,
    rating: 4.9,
    tags: ['Shareable'],
  },
  {
    id: 'bv1',
    name: 'Iced Cold Brew',
    description: 'Slow-steeped cold brew coffee served over ice',
    price: 3.50,
    category: 'beverages',
    image: 'https://images.pexels.com/photos/37022847/pexels-photo-37022847.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 3,
    rating: 4.7,
    tags: ['Popular'],
    popular: true,
  },
  {
    id: 'bv2',
    name: 'Assorted Drinks Combo',
    description: 'Pick any 2: iced coffee, fruit punch, or lemonade',
    price: 5.00,
    category: 'beverages',
    image: 'https://images.pexels.com/photos/31336111/pexels-photo-31336111.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 3,
    rating: 4.5,
    tags: ['Combo'],
  },
  {
    id: 'bv3',
    name: 'Classic Iced Coffee',
    description: 'Freshly brewed coffee chilled with milk and ice',
    price: 3.00,
    category: 'beverages',
    image: 'https://images.pexels.com/photos/4869290/pexels-photo-4869290.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 3,
    rating: 4.6,
    tags: ['Everyday'],
  },
  {
    id: 'd1',
    name: 'Matcha & Chocolate Cake',
    description: 'Layered matcha and dark chocolate cake slices',
    price: 5.50,
    category: 'desserts',
    image: 'https://images.pexels.com/photos/39240989/pexels-photo-39240989.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 2,
    rating: 4.8,
    tags: ['Bestseller'],
    popular: true,
  },
  {
    id: 'd2',
    name: 'Berry Pastry Platter',
    description: 'Assorted pastries topped with fresh berries and fruit',
    price: 6.00,
    category: 'desserts',
    image: 'https://images.pexels.com/photos/5112529/pexels-photo-5112529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 2,
    rating: 4.7,
    tags: ['Shareable'],
  },
  {
    id: 'd3',
    name: 'Bakery Cake Selection',
    description: 'Choose from 3 varieties: chocolate, vanilla, or fruit tart',
    price: 4.50,
    category: 'desserts',
    image: 'https://images.pexels.com/photos/38794905/pexels-photo-38794905.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prepTime: 2,
    rating: 4.6,
    tags: ['New'],
  },
];
